from hypha_startup_services.common.constants import (
    COLLECTION_DELIMITER,
    ARTIFACT_DELIMITER,
    SHARED_WORKSPACE,
    ADMIN_WORKSPACES,
    DEFAULT_LOCAL_HOST,
    DEFAULT_LOCAL_PORT,
    DEFAULT_LOCAL_EXISTING_HOST,
    DEFAULT_REMOTE_URL,
    DEFAULT_WEAVIATE_SERVICE_ID as DEFAULT_SERVICE_ID,
)

# Re-export for backward compatibility
__all__ = [
    "COLLECTION_DELIMITER",
    "ARTIFACT_DELIMITER",
    "SHARED_WORKSPACE",
    "ADMIN_WORKSPACES",
    "DEFAULT_SERVICE_ID",
    "DEFAULT_LOCAL_HOST",
    "DEFAULT_LOCAL_PORT",
    "DEFAULT_LOCAL_EXISTING_HOST",
    "DEFAULT_REMOTE_URL",
]
