COLLECTION_DELIMITER = "__DELIM__"
ARTIFACT_DELIMITER = ":"
SHARED_WORKSPACE = "SHARED"
ADMIN_WORKSPACES = ["ws-user-google-oauth2|104255278140940970953", "aria-agents"]
DEFAULT_SERVICE_ID = "weaviate-test"
DEFAULT_LOCAL_HOST = "https://127.0.0.1"
DEFAULT_LOCAL_PORT = 9527
DEFAULT_REMOTE_URL = "https://hypha.aicell.io"
